version: '3.7'
services:
  my-app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgresql
      - pgadmin
    networks:
      - new

  nginx:
    build:
      context: "nginx/."
      dockerfile: "Dockerfile"
    volumes:
      - nginx:/usr/share/nginx/html/
    ports:
      - "80:80"
    restart: "unless-stopped"
    container_name: "local_nginx"
    networks:
      - new

  postgresql:
    image: postgres
    environment:
      POSTGRES_USER: ${PG_USR}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: flights_db
    networks:
      new:
        aliases:
          - database
    ports:
      - "5432:5432"
    volumes:
      - db-data:/usr/share/nginx/html/

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    networks:
      - new
    ports:
      - "5050:80"
    volumes:
      - db-data:/var/lib/pgadmin/data
networks:
  new:

volumes:
  db-data:
    driver: local
  nginx:
    driver: local