version: '3.7'
services:

  air-travel-delays:
    build:
      context: ./
    container_name: air-travel-delays
    hostname: air-travel-delays
    restart: always
    ports:
      - 5000:80
    networks:
      - network

networks:
  network:
    driver: bridge