version: '3.7'
services:

  air-travel-delays:
    build:
      context: ./
    container_name: air-travel-delays
    hostname: air-travel-delays
    restart: always
    ports:
      - 80:80
    networks:
      - new

  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PG_USR}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: flights_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      new:
        aliases:
          - database

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - new
networks:
  new:

volumes:
  db-data:
    driver: local
  db:
    driver: local